name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  flake8-lint:
      runs-on: ubuntu-latest
      name: Lint
      steps:
        - name: Check out source repository
          uses: actions/checkout@v3
        - name: Set up Python environment
          uses: actions/setup-python@v4
          with:
            python-version: "3.12"
        - name: flake8 Lint
          uses: py-actions/flake8@v2
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker-compose build -t .

